# Generated by Django 2.0.3 on 2018-03-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
