# Generated by Django 2.0.3 on 2018-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pics/%Y-%m-%d/', verbose_name='Profile picture'),
        ),
    ]
