# Generated by Django 2.0.3 on 2018-03-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
