# Generated by Django 2.0.3 on 2018-03-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20180324_2346'),
        ('chat', '0010_remove_chatroom_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
